create table local
(
    id        bigint generated by default as identity
        primary key,
    direccion varchar(255) not null,
    nombre    varchar(255) not null,
    telefono  varchar(255) not null
);

alter table local
    owner to postgres;

create table empleado
(
    id       bigint generated by default as identity
        primary key,
    email    varchar(255) not null,
    nombre   varchar(255) not null,
    telefono varchar(255) not null,
    local_id bigint       not null
        constraint fklffi8q8xbuxo4mtpwdqhnbvtt
            references local
);

alter table empleado
    owner to postgres;

create table modelo
(
    id           bigint generated by default as identity
        primary key,
    costo        numeric(38, 2) not null,
    descripcion  varchar(255)   not null,
    nombre       varchar(255)   not null,
    precio_venta numeric(38, 2) not null
);

alter table modelo
    owner to postgres;

create table inventario
(
    cantidad  integer not null,
    local_id  bigint  not null
        constraint fkn8vslxqp0lnnyq820sx5tgt7a
            references local,
    modelo_id bigint  not null
        constraint fkbno0fw4oajly3bdgmvc2w7g6w
            references modelo,
    primary key (local_id, modelo_id)
);

alter table inventario
    owner to postgres;

create table venta
(
    id          bigint generated by default as identity
        primary key,
    fecha       timestamp(6)   not null,
    total       numeric(38, 2) not null,
    empleado_id bigint         not null
        constraint fk7ingom9xua0w47vxdixw7vtcq
            references empleado,
    local_id    bigint         not null
        constraint fkkp7k0urkkge6n0pbgqac7h15g
            references local
);

alter table venta
    owner to postgres;

create table detalle_venta
(
    id              bigint generated by default as identity
        primary key,
    cantidad        integer        not null,
    precio_unitario numeric(38, 2) not null,
    modelo_id       bigint         not null
        constraint fkp707fpkc9is82pvjmjy8q3ass
            references modelo,
    venta_id        bigint         not null
        constraint fkhj0bf0515yg7equ11ab4xgq3f
            references venta
);

alter table detalle_venta
    owner to postgres;


